env:
- ZMQ="git://github.com/zeromq/zeromq4-1.git" ZMQ_VERSION="v4.1.2" SODIUM="git://github.com/jedisct1/libsodium.git" SODIUM_VERSION="1.0.3" CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- sudo apt-get install uuid-dev
- '[ -z "$SODIUM" ] || git clone --depth 1 --no-single-branch $SODIUM libsodium'
- '[ -z "$SODIUM" ] || cd libsodium'
- '[ -z "$SODIUM" ] || git checkout $SODIUM_VERSION'
- '[ -z "$SODIUM" ] || ./autogen.sh'
- '[ -z "$SODIUM" ] || ./configure'
- '[ -z "$SODIUM" ] || make'
- '[ -z "$SODIUM" ] || sudo make install'
- '[ -z "$SODIUM" ] || cd ..'
- git clone --depth 1 --no-single-branch $ZMQ zmqlib
- cd zmqlib
- git checkout $ZMQ_VERSION
- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo /sbin/ldconfig
- cd ..
language: node_js
node_js:
- "4.2"
- "5.5"
script: travis_retry npm test
